### ISSUE TITLE
Cannot provide default for multi-argument property

### ISSUE THREAD

**Issue by JakeWharton** [ajalt/clikt#1]
`default()` doesn't work after applying `multiple()` and `multiple()` doesn't work after applying `default()`.

I have a list of things that the user can provide, but if none are provided I want to default the list to be something non-empty.

**Comment by JakeWharton** [comment]
Took some poking around but finally found https://ajalt.github.io/clikt/options.html#option-transformation-order which documents this as expected.

**Comment by ajalt** [comment]
As you found, this is expected behavior, although that doesn't mean it can't be improved. If you wanted this behavior, you can still get it like this:
```kotlin
option().transformAll { if (it.isEmpty()) listOf("my default") else it }
```

I could add a default parameter to `multiple`, although that feels kind of inconsistent with the rest of the library. This seems like a common enough use case that it's probably worth adding.
