### ISSUE TITLE
Usability issue with CliktCommand.findOrSetObject() being lazy

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#121]
When in the main command's constructor doing something like

```
init {
    findOrSetObject {
        loadConfig() // Return a populated OrtConfiguration object.
    }
}
```

without any further access of the object, and in the sub-command initializing a member property like

```
private val config by requireObject<OrtConfiguration>()
```

this results in a `KotlinNullPointerException`. The reason is that `CliktCommand.findOrSetObject()` does not actually store the object in the context until it's read for the first time.

While I was able to work around this by calling the underlying `Context.findOrSetObject()` directly in the main command's `run()` like

```
override fun run() {
    context.findOrSetObject { loadConfig() }
}
```

maybe there is a way to avoid API misuse like this altogether?

**Comment by ajalt** [comment]
`CliktCommand.findOrSetObject` returns a property delegate. The issue you're seeing is inherent with all delegates, and I'm not sure there's anything we can do about that.

**Comment by sschuberth** [comment]
I was thinking if `ReadOnlyProperty` in its constructor could already call `Context.findOrSetObject()` once, but it can't because there is no instance of `Context`there yet... anyway, is calling `context.findOrSetObject { loadConfig() }` explicitly the correct / best way to work around this issue in your opinion?

**Comment by ajalt** [comment]
Yes. If you want to set the object eagerly, you should call the function on the context.

**Comment by sschuberth** [comment]
Great, thanks for confirming. To me it's good enough to have this documented here as part of the discussion, so I'm closing this issue.

**Comment by ppslim** [comment]
So this problem has been plaguing me and the docs didn't really help. However, that is a side effect of not looking into the ReadOnlyProperty in more detail to observe the lazy aspect.

Whilst the implementation here with ReadOnlyProperty is lazy, there are no reasons why it cannot be supplemented with an additional eager implementation.

Whilst the nature of this is true by default, the only desired reason for it being lazy in Clikt is because context is not yet initialized & parse it not yet executed, which are desirable states to support access to a computed context and parsed outcome during execution of the delegates block.

Why can findOrSetObject not have an optional eager flag (default false), which when true, registers the delegate to be executed in a pre-run sequence?

So just like when a child sub command is being invoked, the "run" from the parent is invoked (presumably right now because of the details of this very ticket), a pre-run sequences occurs in all parent/children to initialise all registered eager delegates.

This can be done by defining a new interfaces inherited from ReadOnlyProperty, of which the object generated by CliktCommand.findorSetObject is an instance. The interface defines a function that can initialize the value. The new object is then registered when eager, to allow the pre-run sequence to call it.

Whilst this may seem overkill, such a solution is much more elegant and inline with many of the readability principals of Kotlin, but also makes registering such context objects work and feel just like many of other Clikt delegates.

But removing frivolous items from the run function, my run method could be much much more clean

**Comment by ajalt** [comment]
I updated the documentation to mention that the property delegate is lazy, so hopefully this will reduce confusion in the future.

@ppslim Thanks for the input! I'm not a fan of to declaring an unused property just to cause some side effects. I think it's more clear to call the function on your context directly, so I'd rather not add an `eager` parameter to `findOrSetObject `.
