### ISSUE TITLE
Allow to chain conversions

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#133]
For use-cases similar to the one mentioned [here](https://github.com/ajalt/clikt/issues/131) it would be nice if (implicit) `convert()` calls could be chained like so: `.convert { File(it).expandTilde().path }.file()`

As this seems to be a [serious breaking change](https://github.com/ajalt/clikt/issues/131#issuecomment-587656391), I wonder if things would be easier if another function, like `changeValue()`, would be introduced for this purpose that is *not* allowed to change the type.

In any case, it's misleading currently that something like `.convert { File(it).expandTilde().path }.file()` compiles and runs, but silently ignores the first (explicit) conversion. Can we throw an exception if an existing conversion gets replaced?

**Comment by ajalt** [comment]
So there's basically two directions to go with this: enforce the limitation that `convert` can only be called once, or remove it. Currently, the limitation exists, but multiple calls to `convert` will discard all but the last one (multiple calls are only possible if they don't change the type).

### Background

The main reason for the current design is that `convert` has to discard the "each transformer" (like `pair()`) and the "all transformer" (like `multiple()`), since those transformers depend on the value type. So I chose to also discard the existing "value transformer" for consistency. Normally, `convert` changes the option type, and since it's an extension on `Option<String?>`, you can't accidentally call it twice. However, if the conversion doesn't change the type, then the type system doesn't stop you from calling `convert` more than once.

### Preventing multiple calls to `convert`

If we want to be more strict with the current design, we could throw a runtime error (which would be backwards compatible), or enforce it with the type system (which would be source-incompatible)


It would be possible to prevent calling `convert` multiple times by adding a tag into the generics list. For example, something like this:

```
sealed class ValueConversion<T> {
   abstract val transformer: ValueTransformer<T>
   object None: ValueConversion<String>() {
      override val transformer: ValueTransformer<String> = {it}
   }

   data class Transformed<T>(override val transformer: ValueTransformer<T>): ValueConversion<T>()
}

data class OptionWithValues<AllT, EachT: Any, ValueT: Any, TransformValueT: ValueConversion<ValueT>>(
        val valueConversion: TransformValueT,
        val transformEach: ArgsTransformer<ValueT, EachT>,
        val transformAll: CallsTransformer<EachT, AllT>
) 

typealias TransformedOption<AllT, EachT, ValueT> = OptionWithValues<AllT, EachT, ValueT, ValueConversion.Transformed<ValueT>>
typealias NullableOption<EachT, ValueT> = TransformedOption<EachT?, EachT, ValueT>
typealias RawOption = OptionWithValues<String?, String, String, ValueConversion.None>

fun <T : Any> RawOption.convert(...)
```

### Allowing multiple calls to `convert`

It would also be possible to allow multiple `convert` calls by changing `convert` to work like `wrapValue`. If we went this route, we would also change `convert` and all of the conversions like `file()` and `int()` to extend `NullableOption` rather than `RawOption`. This would allow reusing conversion functions. For example, you could do something like `option().file(canBeDir=false).convert { it.readText() }` to automatically read the contents of a file passed on the command line.


### Thoughts

I think allowing multiple calls to `convert` is appealing, since it allows you to reuse conversion functions. It also seems to the behavior that most people intuitively expect. It's also possible to do in a source-compatible way, making the types more strict.

**Comment by sschuberth** [comment]
Thanks a lot @ajalt for these details!

> I think allowing multiple calls to `convert` is appealing, since it allows you to reuse conversion functions.

I totally agree to these thoughts.

However, if you still instead decide to prevent multiple calls to `convert`, I'd simply throw a runtime error.

**Comment by sschuberth** [comment]
Thanks for implementing this so quickly! Now that we can chain `convert()` calls, I wonder if we should revert [tilde expansion](https://github.com/ajalt/clikt/pull/132) again, the argument being that this is just some arbitrary conversion that should be done by the user with an additional `convert()` call. Otherwise people might start demanding that `$HOME` should get expanded, too, etc.

What do you think, @ajalt?

**Comment by ajalt** [comment]
I was was thinking the same thing; the expansion was a bit of a hack.

**Comment by sschuberth** [comment]
BTW @ajalt, the [2.6.0 release notes](https://github.com/ajalt/clikt/releases/tag/2.6.0) miss that tilde expansion introduced in [version 2.5.0](https://github.com/ajalt/clikt/releases/tag/2.5.0) was reverted (in favor of using the more generic chained conversions).

**Comment by ajalt** [comment]
Good catch; I updated the changelog and release notes.
