### ISSUE TITLE
Feature request: ignore undefined options

### ISSUE THREAD

**Issue by mbolotov** [ajalt/clikt#152]
It would be nice if clickt could be configured to ignore undefined options and not throw NoSuchOption in such a case

**Comment by ajalt** [comment]
I don't know, that seems like it would lead to a poor user experience.

If a user makes a typo in an option name, having that option silently discarded would be very surprising.

Similarly, if an command renamed or altered an option, users of the command need to know that the option changed in order to update their scripts that call it.

Do you have any examples of existing command line applications that ignore unknown/mistyped options?

**Comment by mbolotov** [comment]
I don't know if there are many real use cases for that. I just tried to use the library as an intermediate option parser to check if some required arguments are set (and set them automatically if not).
It's an overkill for this usecase to define all the possible parameters.

**Comment by ajalt** [comment]
Can you provide more information on your use case? Maybe there's a better solution.

**Comment by mbolotov** [comment]
I'm developing IntelliJ [plugin](https://github.com/mbolotov/intellij-cypress) for integration with cypress.io
The user of plugin can define arguments in a run configuration and those arguments are passed to cypress binary when the config is being run. There is -b option for the browser to be used by cypress. For certain cases, I have to restrict browser to Chrome only. So I would like to parse the defined parameters by clickt and either set browser to Chrome if no '-b' defined or check the option is set to Chrome.

**Comment by ajalt** [comment]
Thanks for the information, that use case makes sense.

The big problem with unknown options is that we don't know if an unknown option takes any values. So with an argv like `--foo bar`, we don't know if the user meant `bar` as a value of `--foo` or as a separate argument. So we don't want to collect the unknown options separately from arguments.

I could add a boolean property to `CliktCommand` named something like `ignoreUnknownOptions` or `parseUnknownOptionsAsArgs`, that, when `true`, will parse unknown options as arguments. So you would need an `argument().multiple()` property in order to collect them. It's not a perfect solution, but it's the most flexible.

**Comment by mbolotov** [comment]
Okay, that sounds good.

**Comment by paulduffin** [comment]
I'm not sure if I should open a separate issue for this or whether it is working as intended.

I am migrating a tool (`metalava`) to use Clikt and it has dozens if not hundreds of options. I can't convert them all over in one go so I am using Clikt to preprocess the options it knows about and then delegating the parsing of the rest of the options to the old code. That will allow me to incrementally migrate.

The problem is that when I enable help, it adds `-h` as an option and that causes Clikt to start looking for short options. Unfortunately, `metalava` has some options that look like `-new-api` which Clikt tries to treat as a collection of short options and `Parser.parseShortOpt(...)` has the following code:

```
            val option = optionsByName[name] ?: if (ignoreUnknown && tok.length == 2) {
                return OptParseResult(1, listOf(tok), emptyList())
            } else {
                val possibilities = when {
                    prefix == "-" && "-$tok" in optionsByName -> listOf("-$tok")
                    else -> emptyList()
                }
                throw NoSuchOption(name, possibilities)
            }
```

So, it only ignores options that start with a single `-` if they consist of a single letter.

It seems like it would be quite simple to fix this by removing ` && tok.length == 2` but I am not sure if that was intentional.

**Comment by ajalt** [comment]
@paulduffin yes, that behavior was intentional. The reason is that there's no way to know if a token like `-ab` is a group of short options or a single unknown long option.

But I agree that if someone is using `parseUnknownOptionsAsArgs`, they probably never want `NoSuchOption` to be raised. So I implemented your suggestion in 4b0fe73.

I also added a flag `allowGroupedShortOptions` to `Context` in 2968109 which you can use to disable grouped option parsing entirely. If you're using java-style `-long-options`, you might not want grouping.

You can try these out with the [latest snapshot][1].

Finally, if it's just the `-h` name for the help option that's causing issues for you, can [remove that name][2] and just use `--help` (or whichever name you'd like)


[1]: https://github.com/ajalt/clikt/tree/4.0#snapshots
[2]: https://ajalt.github.io/clikt/documenting/#help-option-customization

**Comment by paulduffin** [comment]
Wow, that's amazing. Thank you for your fast response. I tried to use the snapshot to see if it fixed my issue but there were too many differences between it and 3.5.2. I could fix them I am sure but it would not be worth my time at this point as I cannot use a snapshot in this code because it is against our policies as we require a stable build.

Would you be prepared to accept a fix based on 3.5.2 that copies the `treat unknown options as arguments with grouped flag` test from 6f7aa7ab78a79d5df37ebd97f25e40e58ce0d282 and removes ` && tok.length == 2` to make it pass? I'd be happy to create a PR for it but don't want to presume that you have the time to create a 3.5.3 version.

**Comment by ajalt** [comment]
@paulduffin I released 3.5.3 with that change

What issues did you run into when trying 4.0? My goal was to make it source compatible other than the help formatter. If you ran into any incompatibilities, it would be very helpful to let me know what they are so that I can fix them before I release 4.0.

**Comment by paulduffin** [comment]
Most of the source code incompatibilities were around the switch to Mordant.
* `HelpFormatter.render...(...)` methods take an extra `Context`.
* `CliktConsole` has gone, replaced with `Terminal`/`TerminalInterface`.

One weird issue was this option:
```
    val verbosity: Verbosity by
        option(
                help =
                    """
            Set the verbosity of the output.$NEL
                $ARG_QUIET - Only include vital output.$NEL
                $ARG_VERBOSE - Include extra diagnostic output.$NEL
            """
                        .trimIndent()
            )
            .switch(
                ARG_QUIET to Verbosity.QUIET,
                ARG_VERBOSE to Verbosity.VERBOSE,
            )
            .default(Verbosity.NORMAL, defaultForHelp = "Neither $ARG_QUIET or $ARG_VERBOSE")
```

That worked fine on 3.5.2. But with 4.0 it failed with this:
```
Property delegate must have a 'getValue(CommonOptions, KProperty*>)' method. None of the following functions are suitable.
getValue(ParameterHolder, KProperty<*>) defined in kotlin.properties.ReadOnlyProperty
```

If I removed the `: Verbosity` type it worked fine in both. If I changed the type to `: Verbosity?` then it fixed the definition but caused nullabity error.

I tried version 3.5.3 and it fixed the issue I had with using long options with a single leading `-`.

However, it did highlight another problem with using `-?` as an option flag.

If I set `helpOptionNames = setOf("-h", "-?", "--help")` then it works fine.

However, I need to create a non-eager help option as my help formatter depends on some other options (e.g. `--color` and `--no-color` to determine whether to style the help).

If I do the following then it fails in `Option.inferOptionNames()` with `Invalid option name "-?"`:
```
val showHelp by option("-h", "--help", help = "Show this message and exit").flag()
```

I did consider switching the options that affect help to make them eager but I would have to do all the processing myself. So, it was easier to handle help myself.

**Comment by ajalt** [comment]
@paulduffin Thanks for the feedback, it's very helpful!

I updated 4.0 with all of your suggestions:

- I fixed the type annotations that caused the error you saw.
- I added support for options named `-?`
- I changed the `HelpFormatter.formatHelp` method to not take a context; instead the context is passed to its constructor which should simplify the implementation a bit. It's still a different signature from 3.x, though, since help formatting has changed so much.

I plan to release 4.0 soon, but if you have any more feedback about it before then, I'd love to hear it.

**Comment by paulduffin** [comment]
Thanks for that.

> I changed the HelpFormatter.formatHelp method to not take a context; instead the context is passed to its constructor which should simplify the implementation a bit.

I am unclear how that would work with a custom `HelpFormatter` as the instance of that is created in the context builder and so a context is not available at that time. I actually thought that passing in the `context` was good as it meant I could retrieve the `localization` object from there instead of setting it in the context builder and passing it to my `HelpFormatter` override.

I am not sure this is the best place to give you my wish list but here goes (this is based on the 3.5.3 API). I am in the process of migrating a complex CLI tool to using Clikt. It is an iterative process and these are the issues I have found so far.

### Help Formatter

I tried to implement all these myself in a class extending `CliktHelpFormatter` but it was not open enough for me to do that.

1. Allow the width of the `name` column in the help to have a fixed width. At the moment it is the maximum of all the names capped at `maxColWidth`. The problem with that is until you reach the `maxColWidth` adding a new name that is longer than all the previous names causes the help for those previous names to be reformatted which causes a lot of churn in tests of the help formatting.
2. More control over the formatting would be nice, e.g. I would like to add newlines between options, particularly options that have long descriptions.

### Choice options

1. At the moment when defining a `choice` option you have to provide the map from string to value and then duplicate the name of each option in the help. It would be nice if you could provide something like `ChoiceItem(name, value, help)` and then have the help format that list of items with one item per line.
2. Better support for `enum` option - this is currently unusable for me as it either requires the values to be provided on the command line in upper case (which does not match the current CLI of the tool I am migrating to Clikt, and personally I find yucky), or I have to ignore the case which allows them to be specified as lower case but also allows them to be specified as upper case. Instead I have to use a `choice` option and construct the map myself. Maybe allow a `(T) -> String` function to be provided to `enum` which would be used when constructing the choice map.
3. When providing a default it is expected to be of the internal type (as it should) but when generated in the help it is just used as is. It should use the map provided in reverse to select the appropriate output. That does raise the question as to what to do when the internal value can map back to multiple inputs. If the map was ordered I would just say use the first one. At the moment I have to add `defaultForHelp`.

### Lazy Defaults

Sometimes the default can be quite expensive to compute, e.g. looking for a file in some default locations. Or because it depends on the values of other options. It would be nice if there was some way to specify the default for the option lazily so that it would only be computed when necessary. That would of course necessitate use of `defaultForHelp` to provide the description. This can be implemented using a private property for the Clikt option and then a lazy property for the actual value used by the rest of the code but it would be nice to avoid that.

**Comment by ajalt** [comment]
@paulduffin Thanks for the feedback, it's very helpful! Rather than asking you to keep posting on this unrelated issue, I enabled [discussions][4] if you have more feedback in the future. You can also open a new issue if you think that's a better fit.

### Help Formatter

The 4.0 release is pending, which whould make customizing help easier. You can check out [the helpformat sample][3] to see how the context is passed in.


1. If you want a fixed colmn width, you can override `MordantHelpFormatter.buildParameterList` to use a table rather than a definintion list.
2. Formatting tweaks like this should be easier now that everyting is a mordant widget. For example, override `MordantHelpFormatter.renderParameters` and set the `entrySpacing` of the definition list.

### Choice options

1. This is doable, but it would be the only place in the library where we generate a parameter's help text like that. Worth considering if there's other places where that approach could be helpful.
2. Maybe I'm misunderstanding this, but [`enum` does take a `key` lambda][1] that is used to constuct the choice map. `option().enum<E> { it.name.lowercase() }` should do what you want.
3. I can definitely see needing to use `defaultForHelp` to be annoying. I don't think there's any good way to implement a reverse map like you're asking for though, so I think this one is probably going to have to stay the way it is.

### Lazy Defaults

Clikt has this, it's [`defaultLazy`][2]. I'll mention it in the `default` kdoc so that it's easier to find.

[1]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.types/enum.html
[2]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.options/default-lazy.html
[3]: https://github.com/ajalt/clikt/blob/master/samples/helpformat/src/main/kotlin/com/github/ajalt/clikt/samples/helpformat/main.kt
[4]: https://github.com/ajalt/clikt/discussions
