### ISSUE TITLE
docs/whyclikt.md contains factual errors, typos

### ISSUE THREAD

**Issue by xenomachina** [ajalt/clikt#158]
Hello. Author of kotlin-argparser here.

Clikt looks very neat. However, the part of your docs that mention kotlin-argparser contain a factual error. Part of `docs/whyclikt.md` implies that kotlinx.cli "invent[ed] the idea of a property delegate-based cli parser" and says "kotlin-argparser builds off of kotlinx.cli". This is incorrect. If you look at the commit history of both projects you'll see that kotlin-argparser predates kotlinx.cli. (I'd actually never heard of kotlinx.cli until today. Looking at it now, I have to agree that the resemblance is uncanny.)

Also, there's at least one place in your docs where kotlin-argparser is typo-ed as "kotlin-argparse" (missing "r").

**Comment by ajalt** [comment]
Thanks for letting me know! I'll definitely fix the misinformation. 

Since writing that page, kotlinx.cli released a new version that copies some of Clikt's design, so I'm not surprised that their original design came from you. (But, hey, that's what open source is about. I'm glad good ideas are propagating)
