### ISSUE TITLE
Unidiomatic use of exceptions in public API

### ISSUE THREAD

**Issue by dualscyther** [ajalt/clikt#17]
Hi, first of all I want to say that this is a great library with an elegant API, thank you for writing it.

One thing that I want to nitpick is the use of exceptions in the public API. Exceptions live outside of the Kotlin type system (especially because exceptions are unchecked in Kotlin) and I'm not sure that incorrect user input should necessarily be considered exceptional. A simple sealed class which simulates an `Either` type would be a good solution.

Examples of exception abuse:

- https://ajalt.github.io/clikt/utilities.html#input-prompts
- https://ajalt.github.io/clikt/parameters.html#custom-types

I understand that there is more than one way to do things, so maybe you've chosen this design intentionally (in which case just ignore this ;) ), I'm just raising this issue in case you haven't really considered it. I'd also be happy to implement this in a PR.

**Comment by ajalt** [comment]
I'm glad you like it! Thanks for taking the time to think about the api design.

Sealed classes were indeed a design that I considered. I agree that they have some advantages over exceptions, mainly that users can forget to throw the exception. Sealed classes would prevent that mistake. 

I chose to use exceptions for a couple of reasons.

### Implementation simplicity 

`Either` return types work very well when you expect your callers to want to handle both success and failure cases immediately. However, they make it more cumbersome to propagate the result if the callers don't have an immediate use for the value. Exceptions propagate automatically. In the case of Clikt, there are many places that need to halt parsing immediately. It would be onerous to have to check the result of every function call in most of the code base. Instead, we can catch exceptions once in `main` and never need to worry about it.

### Idiomatic considerations

Throwing an exception when you fail to convert a value is a ubiquitous pattern in both the Java and Kotlin standard libraries. (e.g. `String.toInt()`, `Long.parseValue()`). I can't think of any examples of functions returning sealed classes like you suggest.

### Ease of use

3Given the previous point, Clikt's conversion functions catch all exceptions and turn them into `UsageError`s. So if you don't mind a less friendly error message, you can implement `UUID` conversion as simply as:

```kotlin
option().convert("UUID") { UUID.fromString(it) }
```

Since `fromString` already throws an exception, it works fine. On the contrary, if the contract of `convert` was to never throw, but instead return a `Result` sealed class, you would have to do something like this: 

```kotlin
option().convert("UUID") { 
    try { 
        Result.success(UUID.fromString(it)
    } catch (e: IllegalArgumentException) { 
        Result.failure(e.message)
    } 
}
```

 That doesn't seem like an improvement to me.

 ---

 So overall, I think that exceptions are a better API in this case. If I missed something in my considerations, please let me know. I'm always interested in improving the design.

**Comment by dualscyther** [comment]
Cheers for the well thought out (and quick) response!

Regarding your first point, this is something that could probably be solved using Applicative or Monad bind, but that sort of stuff isn't really in the Kotlin stdlib and only exists in the Arrow library (dependencies are probably not a good thing for something small like this)...

In my opinion the biggest argument against using exceptions is:

- they aren't explicitly annotated in the type, making the API a bit less obvious from reading the types alone (not that I'm suggesting people don't read documentation)
- all exceptions get swallowed by Clikt even if the user doesn't want them to be swallowed (however, I'm not sure what use case would require this)

However, your points make a lot of sense, and I definitely didn't consider that existing parsing/conversion functions can be used "as is" without explicit error handling, which is an awesome feature. Besides, your first point alone is probably enough justification already :)
