### ISSUE TITLE
Allow for disabling regex splitting for envvars

### ISSUE THREAD

**Issue by rockwotj** [ajalt/clikt#177]
We sometime use envvars to pass json config to our binaries, not ideal, but where we're at.

The existing behavior to split envvars by whitespace is highly undesirable. This behavior is also not [documented](https://ajalt.github.io/clikt/options/#values-from-environment-variables). In order to work around this we pass in a regex like `Regex("$.")`. Is it possible to disable splitting or only enable it for list parameters?

**Comment by ajalt** [comment]
I definitely agree that it makes sense to only split envvars for `multiple` options, although I'm not sure if it's possible to make that change in a source-compatible way.

**Comment by rockwotj** [comment]
@ajalt do you have a cadence when you do breaking changes?

**Comment by ajalt** [comment]
I don't have plans to make a breaking release right now. But let me write up the problem; there may be a better solution.


Envvar splitting is in kind of a weird place due to differences between windows and unix. On Linux, envars that are lists of files (like `PATH`) are separated with `:`. On Windows, they're separated with `;`.

So Clikt allows `convert` calls (like `path()` and `file()`) to set the envvar split, which overrides the default (splitting on spaces).

But users need to be able to set the split per-option, not just with convert. So if you pass `envvarSplit` to `option()`, that will override both the default and the `convert` split. 

---

I can think of two designs that would improve on the current situation with some breaking changes:

1. Leave the `envvarSplit` parameter in `convert`, but move the one from `option()` into `multiple()`. That still allows you to set the split per-option as well as have the default changes by `convert`.
2. Remove the concept of `envvarSplit` entirely, and instead have you use `option().split()` instead of `multiple()`. This would mean you'd need to manually call `split(System.getProperty("path.separator"))` for file options. It also means that you'd have to call the options differently (`--path=/foo:/bar` rather than `--path=/foo --path=/bar`)

I like option 2, because it's explicit and seems easier to for people understand.

---

We could also change the behavior of passing `envvarSplit=null` to `option()` to cause that to disable envvar splitting. That's a source compatible change, but not much of an improvement on what we have today.

Finally, we could change envvar splitting to only occur with `multiple` options in a source-compatible way if we add a property `val splitEvvar = false` to `OptionWithValues`, but don't add it to the constructor. `multiple` could call `copy` to set it to true. It's hacky, but it would work.

**Comment by rockwotj** [comment]
I agree and really like the appeal of an explicit `split()` command.
