### ISSUE TITLE
clikt.jar is 5 times bigger than similar libraries

### ISSUE THREAD

**Issue by amynbe** [ajalt/clikt#178]
Not an immediate concern for me right now but just wondering.
Looking at https://mvnrepository.com/open-source/command-line-parsers:
Apache commons-cli: 52 KB
JCommander: 81 KB
Kotlin-argparser 87 KB

and...
Clikt: 467 KB

Biggest file is [OptionWithValues.kt](https://github.com/ajalt/clikt/blob/a0c33ab8f4ca341aa9f35deae10e25e2bb683742/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/OptionWithValues.kt) 
and a few other files with similar size, but this library seem to include many files too. What's the likely cause of this? Multiplatform support? Over engineering?

Again, this is not a badly intentioned criticism, I just discovered this library as being the most popular Kotlin arg parser on GitHub, and maintained, and I got a feeling that this is the one, but am just wondering what's wrong with the size of the library.

**Comment by ajalt** [comment]
Clikt uses a composition-over-inheritance design that makes use of uninlineable lambdas. Each extension function like `pair` or `int` calls a function with a lambda argument. Kotlin compiles each lambda to its own class. JVM class files contain a bunch of strings, including a lot of fully qualified class names. 

Even the small classes generated for a lambda are 2-3KB in size when compiled:

```
2.6K 'OptionWithValuesKt$multiple$1.class'
2.1K 'OptionWithValuesKt$option$1.class'
2.4K 'OptionWithValuesKt$pair$1.class'
2.6K 'OptionWithValuesKt$required$1.class'
2.2K 'OptionWithValuesKt$split$1.class'
```

Clikt has a lot of functionality, so the JVM jar contains a couple hundred class files. 

400KB isn't that large, but if you're really concerned about distribution size you should be using a shrinker like ProGuard or R8, which will eliminate all the unused classes. R8 will go even further and combine all the lambdas you do use into [a single class](https://jakewharton.com/r8-optimization-lambda-groups/), further reducing code size.

---

Whether or not Clikt is "over engineered" is subjective, but since you're comparing it to JCommander, lets look at a feature I recently added: [key-value options](https://ajalt.github.io/clikt/options/#key-value-and-map-options).

JCommander calls these "Dynamic options" and their implementation required [hundreds of lines across half a dozen commits](https://github.com/cbeust/jcommander/commits/master/src/main/java/com/beust/jcommander/DynamicParameter.java). Adding unrelated features required [modifying the dynamic options code](https://github.com/cbeust/jcommander/commit/c4ab9804b0b0958a999ceb43fe226ca17ce26e3b#diff-9b682e40ddbed38b302f44439cc48d4e), and there are a number of [open issues](https://github.com/cbeust/jcommander/issues?q=dynamic) relating to bugs that still exist since the implementation is hard to get right given the architecture of that library.

Clikt's implementation is [a single trivial line of code](https://github.com/ajalt/clikt/blob/master/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/OptionWithValues.kt#L531).
