### ISSUE TITLE
Test output of a command

### ISSUE THREAD

**Issue by davioooh** [ajalt/clikt#181]
Is there a way to get the output of a command, to implement unit tests on a CLI?

I'm using `parse` method as suggested in the [docs](https://ajalt.github.io/clikt/advanced/#testing-your-clikt-cli), but I can't understand how to make assertions on output result.

**Comment by ajalt** [comment]
Well, that depends on how you're producing output.

If you're using [echo](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.output/-term-ui/echo/), you can set a [custom console](https://ajalt.github.io/clikt/advanced/#replacing-stdin-and-stdout) during tests that, for example, stores output in a list rather than printing it. You could then assert on the contents of the list.

**Comment by davioooh** [comment]
Thank you. I'll take a try. ☺️

**Comment by rcaught** [comment]
Would it be possible to see a test doing this?

**Comment by rcaught** [comment]
I've found that using https://stefanbirkner.github.io/system-rules/ is the easiest solution.
