### ISSUE TITLE
Clikt versions 2.5.0+ not available on JCenter

### ISSUE THREAD

**Issue by miknoj** [ajalt/clikt#201]
Following version 2.40, it appears the releases of Clikt on [JCenter](https://bintray.com/ajalt/maven/clikt) haven't been kept up-to-date. Would it be possible to make the last few releases available?

**Comment by ajalt** [comment]
JCenter claims to automatically mirror Maven Central (where Clikt artifacts are published), so I'm not sure why it isn't doing that. Is there anything I can do, or is this a problem on their end?

**Comment by alexyu0** [comment]
is it possible that there's some setup/configuration missing that is causing the artifacts to not be mirrored from Maven Central to JCenter? I noticed that new versions stopped being available in JCenter after 2.4.0, in which clikt was no longer directly distributed through JCenter. I also found this [page](https://www.jfrog.com/confluence/display/BT/Maven+Repositories), but not sure if its relevant at all since I'm not that familiar with how Maven Central and JCenter work together.

**Comment by ajalt** [comment]
I emailed Bintray support about this issue; we'll see if they can help.

**Comment by alexyu0** [comment]
any updates?

**Comment by ajalt** [comment]
I'm still going back and forth with their support. They haven't come up with a solution yet. I'll update this issue once I have more information.

**Comment by miknoj** [comment]
Thanks for the support and this awesome library ajalt!

**Comment by ajalt** [comment]
So after a lot of back and forth, it seems that the only way to get jcenter to mirror Maven Central again would be to delete the Bintray repo. That would cause requests for Clikt to jcenter to 404 for some unknown amount of time.

I'd rather not break anyone's builds, so maybe it's better to leave the Bintray repo alone for now. I'm going to change Clikt's maven coordinates in 3.0, which would fix the problem for versions going forward.

**Comment by alexyu0** [comment]
I see, that's unfortunate but thanks for following up! in the meantime, would there be any issues with using version 2.6.0 of the clikt-multiplatform package instead?

**Comment by ajalt** [comment]
@alexyu0 I'm not sure I understand the question. Version 2.6.0 and newer versions of all the clikt packages work fine, but are only available through Maven Central.

**Comment by alexyu0** [comment]
@ajalt sorry let me clarify a bit more. We can access `clikt-multiplatform:2.6.0` through jcenter. Since we can't use `clikt:2.6.0` through jcenter, I was wondering if there would be any issues with using `clikt-multiplatform:2.6.0` instead of `clikt:2.6.0` in terms of differences in behavior?

**Comment by ajalt** [comment]
Thanks for the clarification. If you have a JVM target, I don't think it will work, since the jvm target package isn't mirrored in JCenter. If you are only using JS or native, it should probably be fine, but you'd have to try it out.

Out of curiosity, what prevents you from downloading from Maven Central?

**Comment by alexyu0** [comment]
Got it, thanks! Nothing explicitly, it's just not how our flow is set up right now

**Comment by ajalt** [comment]
Clikt version 3.0.0-rc has been released with the new maven coordinates that will be used going forward.

```
implementation("com.github.ajalt.clikt:clikt:3.0.0-rc")
```

Jcenter should eventually start mirroring these new artifcats.
