### ISSUE TITLE
Creating subcommands does not work

### ISSUE THREAD

**Issue by Partyschaum** [ajalt/clikt#23]
Hi!

I'm trying to get your code example working but it fails with the following error:
```
src/main/kotlin/de/partyschaum/giftcard/domain/giftcard/client/clikt/GitftCard.kt: (22, 10): Expression 'subcommands' of type 'List<CliktCommand>' cannot be invoked as a function. The function 'invoke()' is not found
src/main/kotlin/de/partyschaum/giftcard/domain/giftcard/client/clikt/GitftCard.kt: (22, 10): Cannot access 'subcommands': it is invisible (private in a supertype) in 'Database'
```

Since I'm somewhat new to Kotlin it could be a problem on my side. Anyway, I'm stuck. In case you need more context you'll find the example code [here](https://github.com/Partyschaum/axon-giftcard-example/blob/b6bf6e23fe5755df52d4bf121528fe0e5df15c94/src/main/kotlin/de/partyschaum/giftcard/domain/giftcard/client/clikt/GitftCard.kt#L5-L23).

**Comment by ajalt** [comment]
`subcommands` is and extension function, so you need to import it explicitly with `import com.github.ajalt.clikt.core.subcommands`. The confusing error message is due to the fact that there is also an internal `subcommands` property on `CliktCommand`. I'm going to look into fixing that.

Here's your complete example updated:

```kotlin
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands

class Database: CliktCommand() {
    override fun run() = Unit
}

class Init: CliktCommand(help="Initialize the database") {
    override fun run() {
        echo("Initialized the database.")
    }
}

class Drop: CliktCommand(help="Drop the database") {
    override fun run() {
        echo("Dropped the database.")
    }
}

fun main(args: Array<String>) = Database()
        .subcommands(Init(), Drop())
        .main(args)
```

If you have any more questions, feel free to comment on this issue or open a new one.

**Comment by Partyschaum** [comment]
Thanks! That helped a lot. 👍
