### ISSUE TITLE
Clikt and Kotlin 1.4

### ISSUE THREAD

**Issue by kenyee** [ajalt/clikt#243]
https://github.com/holgerbrandl/kscript/issues/279

This appears to be an issue w/ Clikt using a Kotlin feature that has been changed in Kotlin1.4?

**Comment by ajalt** [comment]
Given that similar issues exist with other combinations of libraries using kscript, (https://github.com/holgerbrandl/kscript/issues/286), this seems like a problem with kscript, not Clikt.

If there's something I can do to help the issue, let me know, but otherwise this seems like it needs to be fixed on their end.

**Comment by kenyee** [comment]
Thanks for the sanity check :-)
