### ISSUE TITLE
Listing more than one mutually exclusive option should generate an error

### ISSUE THREAD

**Issue by asarkar** [ajalt/clikt#251]
```
class OkGrpcCli : CliktCommand(name = "okgrpc-cli") {
    override fun run() = Unit
}

class Listing : CliktCommand(name = "ls") {
    private val kind by option().switch(
        "-s" to "service",
        "-m" to "method",
        "-t" to "type"
    ).default("all")
    private val longListing by option("-l").flag()

    override fun run() {
        echo("$kind $longListing")
    }
}

fun main(args: Array<String>) = OkGrpcCli().subcommands(Listing()).main(args)
```

I expected `main(arrayOf("ls", "-s", "-m"))` to generate an error, but it prints `method false`. Seems like the latter `method` overwrites the former (`service`)

**Comment by ajalt** [comment]
Yes, that's by design. You can use [mutually exclusive options(https://ajalt.github.io/clikt/options/#mutually-exclusive-option-groups) if that's what you need. Keep in mind that enforcing exclusion makes your tool harder to use (e.g. generating arguments programmatically and composing them). I would suggest switching with `switch` if you can.

**Comment by asarkar** [comment]
Hi @ajalt

> that's by design

Even then, I think it's unexpected, since the default behavior is a fallthrough, as happens in Java in absence of `break` statement in `switch`. That's exactly why they've introduced switch expression in Java 12 that doesn't fall through.

I suggest that this ticket be reopened to add support for disabling fallthrough; something like `switch(...).fallthrough(false)`. The default could be true for backward compatibility.
