### ISSUE TITLE
Adding validation for mutually exclusive option groups

### ISSUE THREAD

**Issue by e-g-hategan** [ajalt/clikt#265]
I'm using mutually exclusive option groups as described here
https://ajalt.github.io/clikt/options/#mutually-exclusive-option-groups

but would like to also do parameter validation with validate
https://ajalt.github.io/clikt/parameters/#validate

This doesn't seem to be supported as the returned types are not compatible as far as I can see. 

If I'm wrong and this is in fact possible, please provide an example.

**Comment by ajalt** [comment]
There aren't built-in `validate` or `check` extensions for `MutuallyExclusiveOptions` right now, although you can validate the options in the group individually. Can you share an example of your use case? What are you trying to validate, and what would you want to error message to look like if the validation failed?

The main reason this doesn't exist yet is because I'm not sure if there's a general solution for an error message. For a single option, we print out something like `Invalid option --foo: your error message`. But with an option group, would we add the names of all options to the message? Just the ones you use? It depends on what the specific error message is, which is why there isn't a built-in for this right now.

**Comment by e-g-hategan** [comment]
I am only interested in validating the options in the group individually, here's my example:

```
    sealed class Strategy {
        data class NameBased(val name: String) : Strategy()
        data class IdBased(val id: String) : Strategy()
    }

    private val strategy: Strategy? by mutuallyExclusiveOptions(
        option(
            "--id",
            help = "Name"
        ).convert { Strategy.IdBased(it) }
        // validation required
        ,
        option(
            "--name",
            help = "Id"
        ).convert { Strategy.NameBased(it) }
        // validation required
    ).single()
```

**Comment by ajalt** [comment]
Yes, although you'll need to specify types explicitly, since the `mutuallyExclusiveOptions` parameters are invariant. 

```kotlin
private val strategy: Strategy? by mutuallyExclusiveOptions(
    option("--id", help = "Name")
        .convert<String, Strategy> { Strategy.IdBased(it) }
        .check { (it as Strategy.IdBased).id.isNotEmpty() },
    option("--name", help = "Id")
        .convert<String, Strategy> { Strategy.NameBased(it) }
        .validate { require((it as Strategy.NameBased).name.isNotEmpty()) { "name too short" } }
).single()
```

**Comment by ajalt** [comment]
Ok, I made the parameters covariant in #267, so with that change you'll be able to validate individual options without explicitly specifying the types. Let me know if that solves your problem.
