### ISSUE TITLE
Only prompt for an option when default value is null

### ISSUE THREAD

**Issue by ClausPolanka** [ajalt/clikt#266]
First of all thank you for this great tool. It is really amazing and it makes my life a lot easier.

That said, I was wondering if there maybe is a better way of doing the following:

```Kotlin
when (val authToken = get_token_from_user_properties()) {
    null -> OpenCommand(baseUrl, repoPath).main(args)
    else -> OpenCommandWhenTokenExists(baseUrl, repoPath, authToken).main(args)
}
```
First I tried to do it like this:
```Kotlin
option(names = arrayOf("-g", "--github-token"))
    .prompt("GitHub Authorization Token", default = get_token_from_user_properties())
```
This was almost what I wanted but the app still prompts to confirm the default token (by clicking enter).
Is there a way to avoid prompting for the token when there is one set in a file called user.properties in my app. If this token is not found in the user.properties I want the behaviour of the option which I described earlier.
Thank you very much for your support.

**Comment by ajalt** [comment]
Rather than setting the default value for `prompt`, you can use the [ValueSource][1] API to read parameter values from your user properties. If the parameter is present in the value source, the prompt won't be shown.

P.S. the `names` parameter of `option()` is `vararg`, so you can do `option("-g", "--github-token")` rather than creating an explicit array.

[1]: https://ajalt.github.io/clikt/options/#values-from-configuration-files

**Comment by ClausPolanka** [comment]
Works like a charm. Now I reduced complexity and it works exactly how I want it to work. This tool is amazing. Thank you very much.
