### ISSUE TITLE
No "...-sources.jar" artifact on Maven Central

### ISSUE THREAD

**Issue by dlazerka** [ajalt/clikt#276]
Hi, I've noticed that starting from version 3.0, there's no sources artifact at https://repo1.maven.org/maven2/com/github/ajalt/clikt/clikt/3.1.0/
There was such artifact at
https://repo1.maven.org/maven2/com/github/ajalt/clikt/2.8.0/

Was it intentional? If yes, what's the recommended way to navigate source code from IDE?

**Comment by ajalt** [comment]
Hmm, there should definitely be a sources jar. I'll take a look at the gradle setup.

**Comment by ajalt** [comment]
Ok, the sources jars _are_ being published correctly. There's no sources jar at the location you linked, because that's the metadata publication, which doesn't have any source code associated with it. Sources jars are published for each target individually.

For example, here's the jvm target, and you can see the sources jar is present: https://repo1.maven.org/maven2/com/github/ajalt/clikt/clikt-jvm/3.1.0/

I verified that IntelliJ is able to browse those sources correctly.
