### ISSUE TITLE
Idea: Allow flags to take boolean values

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#280]
Suppose I have a flag like

    val verbose by option().flag()

which can be enabled / set to `true` by passing `--verbose` on the command line. Then sometimes, e.g. when using a UI frontend for a CLI tool where a "verbose" option can be set to "true" or "false" in a form, it would be slightly more convenient to simply pass on that boolean value to the *clikt* option like `--verbose=${boolean_from_ui}` which expands to either `--verbose=true` or `-verbose=false`, instead of implementing logic to use `--verbose` if the UI parameter is `true`, and use an empty string / nothing if the UI parameter is `false`.

So, would it be feasible to make flag options allow to take a [boolean-ish value](https://github.com/ajalt/clikt/blob/ec68e07d4280317eba23bbf043efadfaa99dd6c4/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/FlagOption.kt#L157-L158)? I realize that in some cases like with a flag called "on" allowing something like `--on=off` sounds odd; but then again you'd not *have* to use that syntax.

**Comment by ajalt** [comment]
Clikt doesn't have variable numbers of values for options because it leads to parsing ambiguity, since there's no way to know if the following token is supposed to be the option's value or an argument to the command. 

e.g.

```
val verbose by option().flag()
val source by argument().file()
```

If the user types `--verbose foo`, is the `no` token the a value for `verbose`, or the name of a file?

---

As a partial solution, you can add an off value for your flags (`val verbose by option().flag("--no-verbose")`), which might be easier to work with programmatically.

You could also set the value with an envvar: `TOOL_VERBOSE=false ./tool`

**Comment by sschuberth** [comment]
> If the user types `--verbose foo`, is the `no` token the a value for `verbose`, or the name of a file?

Right. But couldn't this be solved by requiring a `=`between option name and balue? I.e. only allow `--verbose=true` but not `--verbose true`?

**Comment by ajalt** [comment]
That would solve parer ambiguity, but it seems like it pushes the confusion on the the user: now some options require an `=` and some don't. Do you know of any other CLI tools that work that way?

**Comment by sschuberth** [comment]
No, I'm not aware of existing CLI tools that work that way out of my head. I'm trying to push innovative features to *clikt* 😉 That said, JCommander *almost* supports something like that, with its [boolean options with an arity of 1](https://jcommander.org/#_boolean), but then using no value for the options does not work anymore.

**Comment by ajalt** [comment]
I'm on board with adding unique features to clikt, I'm just worried that this one would be confusing for end users. If we allowed `--verbose=true`, what would we do for flags with short names? If someone types `-vno`, is that three flags, or one with an argument? Some people would probably expect the former, and some the latter. Either way, it seems like people will be confused. Today, that situation is unambiguous, since flags never take a value.

**Comment by sschuberth** [comment]
You're right, with all the other features that *clikt* already supports, I also do not see a way to implement this unambiguously. Thanks for evaluating this idea together with me, but it seems fair to me to close this one.
