### ISSUE TITLE
Is there a way to ask again when failing `check` on `prompt` option

### ISSUE THREAD

**Issue by omuomugin** [ajalt/clikt#288]
Since I'm not sure already has this option to do, this is a question for "How to"

My UseCase is like below

When args were implemented like

```
private val name by option().prompt("Name")
        .check("Name should be less than 4 words "){ it.length <= 4 }
```

I want to have behavior like
```
$ cli_tool_made_by_clikt
Name: xxxxx # name by prompt option and should be less than 4 words
Error: Invalid value for Name:  Name should be less than 4 words # want to have failing immediately (1)
Name: # want to have it asking again (2)
```

Anyway thanks for the awesome framework

**Comment by ajalt** [comment]
So I agree that your proposed change is an improvement. The reason for the current behavior is that the lambdas for `check` and `validate` are called after the entire command line has been parsed. This lets you reference other options from those lambdas. 

In order to implement re-prompt after validation failure, we would have to run that option's validation immediately. So there are two approaches:

1. Run the validation for prompt options early, and document the behavior quirk
2. Add a validation lambda to `prompt` specifically. I'm not a fan of this one; it's kludgy and doesn't work well with the rest of the API.

**Comment by omuomugin** [comment]
Ok I understand that behavior.
Let me try implementing this if you don't mind.
