### ISSUE TITLE
Cannot add Clikt to a Kotlin Multiplatform project

### ISSUE THREAD

**Issue by TheOnlyTails** [ajalt/clikt#319]
I'm trying to make a CLI tool with Kotlin and clikt (targeting the JVM, JS - Node, Native - MinGW, Linux and MacOS), and I've added Clikt as a dependency of the `commonMain` source set like so: 
```kt
kotlin {
	// ...
	sourceSets {
		val commonMain by getting {
			dependencies {
				implementation("com.github.ajalt.clikt:clikt:latest.release")
				implementation("com.github.ajalt.mordant:mordant:latest.release")
				implementation("com.squareup.okio:okio-multiplatform:latest.release")
			}
		}
		// ...
	}
}
```
Here is the full `build.gradle.kts`: https://gist.github.com/4a0dfb7628bcf71de92ec9a7e8c3910a

Now, for some reason, when I add deps to any of the source sets, IntelliJ stops recognizing all of them: 
![the `commonMain` source set, unhighlighted like a regular folder](https://user-images.githubusercontent.com/65342367/139697197-8603a816-fd9f-4d73-8b38-efdde7fe6f93.png)
All the multiplatform libraries are gone:
![image](https://user-images.githubusercontent.com/65342367/139697338-c4447e81-3fdb-4290-872f-0df4a2dbfdf5.png)

And the [log](https://gist.github.com/TheOnlyTails/345220c7cb8687f585edc4f22d243e25) shows this error:
```
Failed building KotlinMPPGradleModel
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find clikt-3.3.0-samplessources.jar (com.github.ajalt.clikt:clikt:3.3.0).
```

What is going on here?

**Comment by ajalt** [comment]
I'm not sure this is a problem with Clikt. Maybe try removing all but one dependency (e.g. remove Clikt and Mordant and leave okio) to see if the problem persists.

It looks like you're configuring two native tasks with the same target, which might be causing the issue. (e.g. if run from linux, you're creating both `linuxX64("native")` and `linuxX64()` targets). 

I also see that you're using `js(IR)`. Clikt doesn't currently [support the IR backend due to KT-43490](https://github.com/ajalt/clikt/blob/027e90cf6903453bc23ae7cbea273777e1bed852/clikt/build.gradle.kts#L25-L35). So you'll need to use `js(LEGACY)` for now.
