### ISSUE TITLE
linuxArm64 target support

### ISSUE THREAD

**Issue by ethanmdavidson** [ajalt/clikt#324]
Are there any plans to support the linux arm64 target? Are there any blockers holding this back?

**Comment by ajalt** [comment]
I don't have plans to support that target.

1. There are no GHA runners for that target, and I'd rather not publish artifacts without CI tests
2. Most other libraries don't support the target either, so adding it would prevent Clikt from using them as dependencies (e.g. if I wanted to add coroutine functionality, I wouldn't be able to do so since kotlinx.coroutines doesn't support linuxArm64)

That being said, if you want to compile it yourself, you should be able to do so by adding the target to gradle and copying the [linuxX64][1] native code to the new source directory.

[1]: https://github.com/ajalt/clikt/tree/master/clikt/src/linuxX64Main/kotlin/com/github/ajalt/clikt/output

**Comment by ethanmdavidson** [comment]
Thanks for the quick response! I completely understand your position, especially given point 2. It's really a shame that Kotlin isn't going for arm targets very strongly.

For anyone else who comes across this, I took a crack at this (and macosArm64) last night and there weren't any compile errors. However, it seems like kotest also doesn't support either arm target yet so I wasn't able to run the tests.
