### ISSUE TITLE
exitCode for bad parameters

### ISSUE THREAD

**Issue by sergeych** [ajalt/clikt#325]
Thanks for an excellent tool. There is noe small problem: when we use something like

        val source: File? by argument().file(mustExist = true, canBeDir = false).optional()

If the file is not found or whatever check is failed, the exit status of the application is still 0, what is, in many cases, not good. Could you please provide either the global setting to set exit code on check failed or let us provide exit code for any argument with checks? Thanks in advance.

**Comment by ajalt** [comment]
Hm, I can't reproduce this.

For example:

```kotlin
class Cli : NoOpCliktCommand() {
    val file by argument().file(mustExist = true, canBeDir = false).optional()
}
```

```
$ ./cli ./missing
Usage: cli [OPTIONS] [FILES]

Error: Invalid value for "FILE": Path "./missing" does not exist.

$ echo $?
1
```

Can you share a complete example like this that exhibits the problem?

In general, you can override [`main`][1] and return whatever exit code you'd like. By default, Clikt exists with a status code of 1 any time it prints an error, and 0 otherwise.

[1]: https://github.com/ajalt/clikt/blob/4b909c22837d01a36e1c4e22be3cbff1842a77bc/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L408-L433
