### ISSUE TITLE
Missing features not documented in Kotlin/Native

### ISSUE THREAD

**Issue by amirabiri** [ajalt/clikt#370]
`path()` and `file()` appear to only be available in JVM, but this isn't mentioned in the docs:

https://ajalt.github.io/clikt/advanced/#multiplatform-support

**Comment by ajalt** [comment]
They're JVM-only because they return `Path` and `File` instances, which are java classes. The [API docs][1] do have the platform tags on them, but I agree that it could be helpful to mention that in the markdown.

[1]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.types/file.html
