### ISSUE TITLE
Make flag option 'required'able in certain context

### ISSUE THREAD

**Issue by Difocd** [ajalt/clikt#391]
It's not possible to apply 'required' to a flag option. That's resonable.

But in certain circumstance, like [Co-Occurring Option Groups](https://ajalt.github.io/clikt/options/#co-occurring-option-groups), a 'required' option in group is not really 'required' from cli. Sometimes, a 'required' flag is more self explanatory than anything else.

For example:

```kt
class Engine1Options : OptionGroup() {
    val enableEngine1 by option().flag()
    val engine1Arg1 by option()
}

class Engine2Options : OptionGroup() {
    val enableEngine2 by option().flag()
    val engine2Arg1 by option()
}
```

Usage:

```shell
./tool --enable-engine1 --engine1-arg1 foo --enable-engine2 --engine2-arg1 bar
```

I tried a compromise:

```kt
class Engine1Options : OptionGroup() {
    val enableEngine1 by option().convert { it.toBoolean() }.required()
    val engine1Arg1 by option()
}
```

But it can be wired when:

```shell
./tool --enable-engine1=false --engine1-arg1 foo
```

**Comment by ajalt** [comment]
Sounds like you want [groupChoice][2] or [groupSwitch][2]

[1]: https://ajalt.github.io/clikt/options/#choice-and-switch-options-with-groups
[2]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.groups/group-switch.html

**Comment by Difocd** [comment]
> 

groupChoice and groupSwitch only allow one group chosen. Like:
```kt
option().groupSwitch("--foo" to FooOptionGroup(), "--bar" to BarOptionGroup())
```
If I use `./tool --foo --bar` in cli, only BarOptionGroup is chosen

**Comment by fxshlein** [comment]
Hi @ajalt!

We're running into a very similar issue, where we want to allow the user to specify multiple co-occurring option groups, thus we cannot use the group switch.

We have the special situation that the actual option groups are provided by other modules, and that module will be enabled when the option group property is not null.

Essentially, we have properties like this:
```kt
val moduleAOptions by OptionGroupModuleA().cooccurring()
val moduleBOptions by OptionGroupModuleB().cooccurring()
```

And then use them like this:
```kt
if (moduleAOptions != null) {
    // run module A with options
}

if (moduleBOptions != null) {
    // run module B with options
}
```

Now, the options for module A could look like this, which is of course supported:
```kt
class OptionGroupModuleA : OptionGroup() {
    val somethingModuleA by option().required()
    val somethingOptionalForModuleA by option()
}
```

But now module B does not actually need any options, so we would like to do this:
```kt
class OptionGroupModuleB : OptionGroup() {
    val enableModuleB by flag().required()
}
```

We would like to keep this separation (the other modules providing their `OptionGroup`) in favor of using flags for the specific modules that don't require options, because then we don't have to change the CLI module if modules do end up requiring/no longer requiring options.

**Comment by ajalt** [comment]
@fxshlein thanks for the details.

You can't make a flag required since it always has a default, but using the `boolean()` option type added in the 4.0 branch, you can make your own required flag:

```kotlin
class OptionGroupModuleB : OptionGroup() {
    val enableModuleB by option().boolean()
        .transformValues(0..0) { true }
        .required()
}
```

You can try out the 4.0 branch with a [snapshot build][1]

[1]: https://github.com/ajalt/clikt#snapshots
