### ISSUE TITLE
Error: no such option: "-e".

### ISSUE THREAD

**Issue by terrakok** [ajalt/clikt#396]
With default library setup, the following call behaves strangely:
```
./my_tool -help
Error: no such option: "-e". Did you mean "--help"?
```

It can be reproduced in https://github.com/Kotlin/kdoctor

**Comment by ajalt** [comment]
The error tells you exactly what's wrong: you're typing `-help` with one dash instead of `--help` with two, so it's parsed as `./tool -h -e -l -p`. This behavior is documented here: https://ajalt.github.io/clikt/options/#boolean-flag-options

If you actually want java-style long options with a single dash, you can configure that too:
https://ajalt.github.io/clikt/options/#windows-and-java-style-option-prefixes
