### ISSUE TITLE
Customizing exit codes

### ISSUE THREAD

**Issue by saem** [ajalt/clikt#44]
Thanks for writing this library. I was wondering if you have / would consider making it possible to test error handling and custom return codes?

The idea is when implementing a `CliktComand` or including it into another library / framework for their users would want to do the following:
- Provide a facility for custom exit codes, making it easier for automation down the road to use that to make decisions, for instance some errors might be worth retrying
- Test that error messages and codes are being generated correctly, this is mostly checking exception logic

# Challenges & Possible Solutions
Challenges I've encountered so far and some thoughts towards a solution, but those solutions themselves have accompanying issues:
- main functions in CliktCommand are final making it hard 
- main(List<String>), parse, and run do not return numbers so exit codes can't be seamlessly passed through
- CliktError, Abort, and friends don't accept return codes -- these should probably be optional parameters (defaulted to current codes)
- main(List<String>) calls exitProcess making the logic not testable indirectly (less of a concern for library consumers) but going down a path of an extensible and testable strategy it might be worth returning the exit code to main(Array<String>) and it having a single exitProcess: 
```kotlin
fun main(argv: List<String>): Int { /* snip */ }

fun main(argv: Array<String>) = exitProcess(main(argv.asList()))
```

I can completely understanding being hesitant about adding return parameters to these functions as they're the entry point everyone uses, but the breakage should be very easy to fix. **I can create a speculative pull request if you want to see what a possible set of changes might look like and we can see what options there might be.**

# What I've Tried
Below is an example where I've done it from as a consumer of the library, this is within the broader context of me creating a tiny web framework mimicking Dropwizard's single fat jar which allows you to run migrations, start an application server, add custom sub-commands, etc...
```kotlin
import com.github.ajalt.clikt.core.CliktCommand
import kotlin.system.exitProcess

abstract class Command (
        help: String = "",
        epilog: String = "",
        name: String? = null,
        invokeWithoutSubcommand: Boolean = false
    ): CliktCommand(
        help = help,
        epilog = epilog,
        name = name,
        invokeWithoutSubcommand = invokeWithoutSubcommand) {

    companion object {
        const val SUCCESS = 0
        const val COMMAND_PARSING_ERROR = 1 // used by Clikt
        const val ERROR_WHILE_COMMAND_RUNNING = 2
    }

    /**
     * Implement [doRun] and don't use [main]
     */
    final override fun run() {
        val exitCode = try {
            doRun()
        } catch (e: Exception) {
            exceptionHandler(e)
        }

        exitProcess(exitCode)
    }
    
    abstract fun doRun(): Int
    
    open fun exceptionHandler(e: Exception) = ERROR_WHILE_COMMAND_RUNNING
}
```

**Comment by saem** [comment]
I can raise a separate issue if necessary but as I was replicating the Clikt exception handling, printing and exit code handling in another experiment to work around things I found a potential bug:

Abort always returns in an error and error exit code here:
https://github.com/ajalt/clikt/blob/master/clikt/src/main/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L182
But in the API docs for Abort, it should only do so if the error boolean is set (by default it is):
https://github.com/ajalt/clikt/blob/master/clikt/src/main/kotlin/com/github/ajalt/clikt/core/exceptions.kt#L10

It's small, but even if a whole sale change isn't made around exit codes I'm happy to help refactor a bit and test it.

**Comment by ajalt** [comment]
Thanks for reporting the issue with `Abort`. I fixed it in 72d4f55.

Error codes are the normal mechanism that shells use to communicate failure. Exceptions are the normal mechanism that kotlin code uses to communicate failure. Error codes don't carry useful information, and don't compose well due to the possibility of collisions. 

I think the most maintainable way to handle failure in commands is to throw exceptions in your code and catch them all in one place. This is how the `ClickCommand.main` function works. If you want to deal with failure differently, then I would suggest calling `parse` instead of `main` in your program's `main` function, and exiting with whatever status codes you'd like there. This allows you to customize exit codes without worrying about collisions, and without any of your command code needing to know that custom exit codes are being used.

**Comment by saem** [comment]
Thanks, @ajalt. I didn't really consider composition makes sense. I also learned about how one can intercept exitProcess calls in jUnit so that's fun which should also make testing this a whole lot easier.

**Comment by sschuberth** [comment]
> Error codes are the normal mechanism that shells use to communicate failure. Exceptions are the normal mechanism that kotlin code uses to communicate failure. Error codes don't carry useful information, and don't compose well due to the possibility of collisions.

I'm still wondering why the design choice was made to not give a *clikt* user explicit control over the exit code. Command line tools are often called from scripts which do further processing, and in the script we could know that exception *X* corresponds to exit code *Y*, and handle the exit code accordingly.

A simple way to address this would be to add a nullable `exitCode: Int? = null` property to `UsageError` and use that `exitCode` in `CliktCommand.main()` if set instead of hard-coding `1`.

**Comment by ajalt** [comment]
@sschuberth Clikt users **do** have full control of exit codes. If you want different exit codes, call [parse](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/parse/) instead of [main](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/main/), [catch CliktExceptions](https://github.com/ajalt/clikt/blob/425b28234eb4bf03887a5f9b07455d50439d0b84/clikt/src/main/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L229-L248), and exit with whatever values you want.

**Comment by sschuberth** [comment]
Right, I should have said "explicit control in a *convenient* way" 😉 No offense, but to me, exit code handling should be a first-class feature for a CLI tool, whereas currently it requires quite some custom code compared to `throw UsageError(text = "Usage error", exitCode = 2)`, or simply requiring `run` to return an `Int` which is used as the exit code.

**Comment by ajalt** [comment]
@sschuberth I added a `statusCode` property to `UsageError` in 
e291285. Let me know if that covers your use case. You can try out the snapshot build with [JitPack](https://jitpack.io/#ajalt/clikt/master-SNAPSHOT)

**Comment by sschuberth** [comment]
Superb @ajalt, thanks a lot! That works for me :smiley:
