### ISSUE TITLE
Default values for path options are not checked

### ISSUE THREAD

**Issue by XhstormR** [ajalt/clikt#441]
I have a path option that provides a default value, and set `mustBeReadable` to true, when I run the program directly without providing an option, the option is not checked.

```kotlin
object App : CliktCommand() {

    private val sourceDir by option().path(mustBeReadable = true).default(Path("/source")) // source folder does not exist

    override fun run() {
        echo(sourceDir)
    }
}

fun main(args: Array<String>) = App.main(args)
```

**Comment by ajalt** [comment]
I don't think there's a way to build this in: since you can chain conversions on an option, the path checks have to be done when the value is converted (before the default is applied). But you can do this manually in `validate` pretty easily:

```kotlin
val sourceDir by option().path().default(Path("/source")).validate {
    require(Files.isReadable(it)) { "Path is not readable" }
}
```

`validate` is called with the final option value, even if it's from the default.
