### ISSUE TITLE
clikt 4.X grew in jar size to over 8mb

### ISSUE THREAD

**Issue by arturbosch** [ajalt/clikt#507]
Hi,

first of all, like https://github.com/ajalt/clikt/issues/178, I also consider this to be the most ergonomic cli parsing library out there! Thanks for making it!.

I just noticed that my bundled dependencies grew by a lot.
Some investigations led to clikt:

![clikt-deps](https://github.com/ajalt/clikt/assets/20924106/44870261-ec39-4625-be31-899d8a1f2029)

and it's transitive dependencies like:

![deps-size](https://github.com/ajalt/clikt/assets/20924106/fae0ed85-dbc8-419f-8b64-f45d2ddbf20f)

As far as I understand the new markdown feature introduced in 4.0 led to the increase of dependencies.

Is it still possible for you to make the markdown (other visualization methods than just text) optional?

**Comment by ajalt** [comment]
Thanks for the kind words!

I don't have plans to make mordant optional, because I don't want to maintain a second copy of all the multiplatform terminal output, text formatting, and help formatting.

I'm curious, what does your project look like that a couple MB of package size matters?

**Comment by ajalt** [comment]
Mordant is Clikt's only dependency. It provides multiplatform output, prompting, text color and formatting, markdown rendering and more.

It's also part of Clikt's public API, so there's no easy way to make it optional. Even if I did, you'd have to supply your own help formatter, prompt implementation, etc. Would you willing to write all that code just to remove a single dependency? 

If binary size is important, you should be build with R8 or proguard, which would eliminate all the unused code and make removing mordant mostly pointless anyway.

**Comment by ajalt** [comment]
I do minimize dependencies; Mordant is Clikt's only direct dependency, and I plan on keeping it that way. I don't even use common libraries like kotlinx.coroutines.

I've experimented with a zero-dependency core module in the past, but given how much functionality you'd lose, I'm skeptical that's there's actually a strong enough use case to justify the extra maintenance burden.

**Comment by JakeWharton** [comment]
I see two potential and separate improvements that I think could be argued for:

1. The fastutil dep by JB markdown is egregious. I haven't looked, but I can guarantee this library is barely used and likely as premature optimization (as opposed to plain boxing collections). I would advocate for them to copy in one specialized version as needed, if needed.

2. The markdown support baked into mordant core is a little weird. It should likely be layered _above_ the core in a separate artifact (which still could be a mordant artifact). In the past I've talked about how the markdown support in Mordant uses private APIs to accomplish things you can't do with the public API. This is not the case today, probably, but being a separate artifact all but guarantees the APIs in Mordant core are suitable for similar downstream usage. Markdown isn't related to the goal of rich terminal rendering, but it's one opinionated format which can use it.

Now let's say both of those changes are made, there's one more argument:

Should Clikt have built-in markdown parsing? Personally I have only used this once. I think you could probably argue that the built-in help should respect double newlines but otherwise reflow text. Separately, a `markdownHelp` (or whatever) extension could live in clikt-markdown and depend on mordant-markdown.

Whether that happens I think is less important than the first two points. Those seems like pretty clear wins.

**Comment by JakeWharton** [comment]
> 1. The fastutil dep by JB markdown is egregious. I haven't looked, but I can guarantee this library is barely used and likely as premature optimization (as opposed to plain boxing collections). I would advocate for them to copy in one specialized version as needed, if needed.

😀 https://github.com/JetBrains/markdown/pull/155
