### ISSUE TITLE
Print default value in usage

### ISSUE THREAD

**Issue by andness** [ajalt/clikt#53]
I think the default value for options would be a very useful part of the help output, but I've not found a way to achieve this. Any trick I'm missing, or is it just not possible?

**Comment by ajalt** [comment]
That does seem useful. It's not built in to the help formatter, but you could do something like this:

```kotlin
fun <EachT : Any, ValueT> NullableOption<EachT, ValueT>.defaultWithMessage(value: EachT)
        : OptionWithValues<EachT, EachT, ValueT> {
    return transformAll { it.lastOrNull() ?: value }.run {
        copy(transformValue, transformEach, transformAll, help = "$help (default: $value)")
    }
}
```

Which you would use instead of `default`, like this:

```kotlin
val opt by option(help="my option").defaultWithMessage("def")
```

And would result in this help page:

```
Usage: program [OPTIONS]

Options:
  --opt TEXT  my option (default: def)
  -h, --help  Show this message and exit
```

**Comment by dbogdoll** [comment]
This function seems not to work with option().switch().
Also it would be great if we could create the message lazily, so instead of
.defaultWithMessage { "lazy created message) }.
Even better if we could provide not a message, but the default object and optional an object_to_string converter.
E.g. what I wanted to have was a 
option().switch("--mock" to Type.Mock, "--regular to Regular").defaultValue { Type.Mock }

The defaultValue also creates the default lazily.

**Comment by ajalt** [comment]
Well, here's one that works for flag options life `switch`:

```kotlin
fun <T : Any> FlagOption<T?>.defaultWithMessage(value: T): FlagOption<T> {
    return FlagOption(names, secondaryNames, "$help (default: $value)", hidden, envvar,
            transformEnvvar = { transformEnvvar(it) ?: value },
            transformAll = { transformAll(it) ?: value })
}
```

But since the help message is created as soon as the function is called, there isn't any way to make the message lazily.

**Comment by ajalt** [comment]
Thanks for the suggestion! I added this in 5be9f34, which is part of the 2.0.0 release. 

Docs: https://ajalt.github.io/clikt/documenting/#default-values-in-help

I decided not to support lazy help messages, since it would complicate the implementation.
