### ISSUE TITLE
Arguments in parent command are not accepted when subcommand is present

### ISSUE THREAD

**Issue by juraj-hrivnak** [ajalt/clikt#543]
When running the `parent `command with any argument: `$ ./tool parent arg`, the command is not run, but the help message is printed instead.

If we comment out the `this.subcommands(Subcommand())` this starts to work properly.

Using `$ ./tool parent arg subcommand` for some reason accepts the argument. That is weird because `allowInterspersedArgs` is set to `false `by default.

Source code:
```kotlin
class Subcommand : CliktCommand()
{
    override fun run() = Unit
}

class Parent : CliktCommand()
{
    private val args: List<String> by argument("arguments").multiple()
    override fun run() = Unit

    init
    {
        this.subcommands(Subcommand())
    }
}
```

Note that I tried both the latest & latest snapshot versions.

**Comment by ajalt** [comment]
Thanks for the clear reproduction.

This is by design; you can't specify parent arguments after a subcommand because it would lead to ambiguity if the subcommand also had any arguments. `arg subcommand` is fine because the argument occurs before the subcommand. `allowInterspersedArgs ` only affects arguments and options, not subcommands.

**Comment by juraj-hrivnak** [comment]
I see, that makes sense. The issue is the argument doesn’t work when the subcommand is not used.

**Comment by ajalt** [comment]
You need to enable [running the parent without children][1]

[1]: https://ajalt.github.io/clikt/commands/#running-parent-command-without-children

**Comment by juraj-hrivnak** [comment]
So that's the trick! Thank you,
