### ISSUE TITLE
Excessive Mordant dependencies by default on JVM

### ISSUE THREAD

**Issue by mikaelstaldal** [ajalt/clikt#559]
When depending on Clikt on JVM, you get not only Mordant core, but also all three different Mordant implementations on your classpath:
* mordant-jvm-ffm
* mordant-jvm-jna
* mordant-jvm-graal-ffi

What about depending only on `mordant-core` by default? I guess that should be enough for basic functionality of Clikt.

**Comment by ajalt** [comment]
A lot of mordant's functionality on JVM requires one of those modules. You can exclude the jvm modules through gradle, though, and it will still compile.

**Comment by mikaelstaldal** [comment]
But does Clikt's functionality require one of those modules?

**Comment by ajalt** [comment]
The only parts of the JVM modules that Clikt uses are for terminal detection. Without them, it won't be able to detect the terminal size, so words will always wrap at 79 columns, and it won't be able to detect if the terminal is interactive, so if you redirect output to a file, it will print ANSI codes to the file instead of plaintext.

**Comment by mikaelstaldal** [comment]
Ah, OK. Good to know.

If you don't want this, you are supposed to use `clikt-core`?

**Comment by ajalt** [comment]
That's another option, although clikt-core has [even more limited functionality][1]

[1]: https://ajalt.github.io/clikt/advanced/#core-module
