### ISSUE TITLE
Retrieve values from file instead of envvar ?

### ISSUE THREAD

**Issue by nsteinmetz** [ajalt/clikt#78]
Hello,

New to Kotlin, I'm building an installer for an app with your tool. I was wondering if it would be possible to retrieve values from a file instead of envvars ? I saw #59 so I could first load my file content as env variables but I would prefer to have access to the file, especially as it's a yaml file with nested values in it.

Any idea on how to implement this use case ?

Global idea is : if values are in the file, use them, and if not prompt for them.

Thanks !

**Comment by nsteinmetz** [comment]
I think I have to use `Context`to pass the info from file to functions. However seems I cannot access data in cust before we're in the `run()` function.

I'm not sure also about combining "prompt" and "default" together ? Seems they don't work together.

So my idea would be something like :

If default value is set, then don't prompt :
```
val name by option(help="Customer's name").default(cust["CUSTOMER"].name).prompt()
```

or do some if/else logic but it does not seem supported.

```
if cust["CUSTOMER"].name {
    val name by option(help="Customer's name").default(cust["CUSTOMER"].name)
} else {
    val name by option(help="Customer's name").prompt()
}
```

Whole code below:

```
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.core.findObject
import com.github.ajalt.clikt.core.requireObject

import java.io.File

import kotlinx.serialization.json.*

fun getContentFromFile(fileName: String): Customer {
    val file = File(fileName)
    val content: String
    val obj: Customer

    if (file.isFile) {
        content = file.readText()
        val json = Json(JsonConfiguration.Stable)
        obj = json.parse(Customer.serializer(), content)
        return obj
    } else {
        return Customer("", "", "")
    }
}

class Configurator: CliktCommand() {
    val fileName : String = "saagie.mdl"
    val config by findObject { mutableMapOf<String, String>() }
    val custData = getContentFromFile(fileName)
    val cust by findObject{ mutableMapOf<String, Customer>() }
    override fun run() {
        config["FILENAME"] = fileName
        cust["CUSTOMER"] = custData
    }
}

class InitCustomer: CliktCommand(help="Initialize the customer") {
    val config by requireObject<Map<String, String>>()
    val cust by requireObject<Map<String, Customer>>()
    val name by option(help="Customer's name").prompt()
    val domain by option(help="Root Domain name: ex  bigcorp.com").prompt()
    val subdomain by option(help="instance name ; ex <instance>-beta.bigcorp.com").prompt()

    override fun run() {
        val cname = cust["CUSTOMER"]?.name
        echo(cname)
        val json = Json(JsonConfiguration.Stable)
        val jsonData = json.stringify(Customer.serializer(), Customer(name, domain, subdomain))
        val file = File(config["FILENAME"])
        file.writeText(jsonData)
    }
}

class Drop: CliktCommand(help="Drop the database") {
    override fun run() {
        echo("Dropped the database.")
    }
}

fun main(args: Array<String>) {
    Configurator().subcommands(InitCustomer(), Drop())
        .main(args)
}
```

**Comment by ajalt** [comment]
`prompt` and `default` don't make sense together: they both provide a non-null value when the option isn't present.

In your particular case, you could do something like this:

```kotlin
val name by option(help="Customer's name").run {
    val n = cust["CUSTOMER"]?.name
    if (n == null) prompt()
    else default(n)
}
```

That's kind of ugly, but you could extract it into an extension function.

# Config files

The only currently built-in way to read command line values from a file is with [@-files](https://ajalt.github.io/clikt/advanced/#command-line-argument-files). 

I definitely agree that it would be nice to support configuration files as a fall-back. Gradle, for example, does this with it's `.properties` files. However, there are a number of API tradeoffs that need to be considered. Here are a few:

1. Supporting different file types (properties, toml, json, yaml, etc.). Do we build in support for any formats, and if so, which parsers would we use? If not, then we'd need to provide modules for each format and a way to register them with your commands.
1. How would you specify the keys for each option? Envvars have the `autoEnvarPrefix` and the `envvar` parameter on various functions, but each file format could potentially have a different key format. Do we allow multiple keys for the same option?
1. Should we support multiple config file types in the same command, or restrict each command to a single parser? If we allow multiple file types, can you specify different keys for each type?
1. How would this work with subcommands? Should each subcommand be able to specify different files, or should that live on the Context?
1. How would value conversion work? Options and arguments expect all their values to come in as strings, which are then converted with functions like `int()`. But most configuration file parsers will already do value conversion. Should we call `toString` on whatever the parsers give us so that we can run it back through our parameter conversions?
1. How should file parsing errors be handled? Git will crash if your gitconfig doesn't parse, but gradle will still run if it can't read a `gradle.properties` file.
1. How should you specify the location of the files? Should we support specifying a file location in an option itself, or only in code when constructing the command?

I think this would be a great feature if we can solve all the problems with the API design. I'd love to see prior art if you know of any.

**Comment by nsteinmetz** [comment]
Thanks for your answer - Will use it tomorrow as I will need default for some prompt lines ;-)

I ended up doing differently in the mean time :
* I load my property files and validate content against my data classes.
* If it's valid, I do nothing more
* It it's not valid, I trigger the command.

Design question are challenging indeed - no particular experience in this topic. So not sure I can provide any additionnal help here :-/
