### ISSUE TITLE
TermUi.editText() freezes on macOS

### ISSUE THREAD

**Issue by iampravikant** [ajalt/clikt#99]
`TermUi.editText("Hello world!")` will freeze on macOS.
seems like an issue in ProcessBuilder

**Comment by sebokopter** [comment]
I've also had a look into this and can confirm this also exists in (Ubuntu) Linux and I've rechecked against MacOS too.

Actually this is an issue for all Unix/Linux but only for CLI editors like vi(m), nano, ... 

Here's why:
Java's ProcessBuilder#start() creates a new subprocess (both in Java as an instance of the Process class but also on the *nix system).
When you call from a terminal a clikt application (parent) the input and output streams of those subprocess is not accessible since the terminal is still connected to the input and output streams of the clikt application (parent).

For GUI editors that is not an issue since they are starting a window with which you interact besides the Terminal respectively the Terminal-attached clikt application.

Setting the streams (input, output, error) to redirect will redirect the terminal input and output from the clikt application (parent) to the CLI editor (child).

btw: instead of calling ProcessBuilder#redirect*() for every stream you could use ProcessBuilder#inheritIO() which redirects all streams at once.
